/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CandidatarRouteImport } from './routes/candidatar'
import { Route as IndexRouteImport } from './routes/index'

const CandidatarRoute = CandidatarRouteImport.update({
  id: '/candidatar',
  path: '/candidatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidatar': typeof CandidatarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidatar': typeof CandidatarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidatar': typeof CandidatarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candidatar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidatar'
  id: '__root__' | '/' | '/candidatar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatarRoute: typeof CandidatarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/candidatar': {
      id: '/candidatar'
      path: '/candidatar'
      fullPath: '/candidatar'
      preLoaderRoute: typeof CandidatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatarRoute: CandidatarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
